"""Create table review

Revision ID: 851d91090ede
Revises: 
Create Date: 2020-10-13 00:03:35.465437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '851d91090ede'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('author', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('product_name', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('review', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('rating', mysql.TINYINT(display_width=3, unsigned=True), nullable=False),
    sa.Column('location', sa.String(length=768, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_reviews_author'), 'reviews', ['author'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_updated_at'), 'reviews', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_updated_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
